name: Update DB entries
on: workflow_dispatch
jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages 🔧
        run: npm install

      - name: Update Data 🆕
        run: npm start
        env:
          REPO_AND_BRANCH: ${{ secrets.REPO_AND_BRANCH }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}